### ISSUE TITLE
2MB

### ISSUE THREAD

**Issue by zhxmrpig** [lysannschlegel/RDAExplorer#14]
1、Open “Data17.rda”
2、Save AS “DATA172.rda”

“Data17.rda”  :  3617440KB
"Data172.rad" : 3615963KB
Why?  Smalled 2MB

OS:Windows 10 P X64 Simplified Chinese
Visual Studio: 2019 P

Cloud you give me EXE?
Thank you!

**Comment by lysanntranvouez** [comment]
When the RDAExplorer writes the archive back, it does not remember if the files were compressed in the original RDA archive, and it will also group them differently. [The code for writing is here](https://github.com/lysannschlegel/RDAExplorer/blob/fbc1d7be320b7654382504d765cd8fa309931395/src/RDAExplorer/RDAWriter.cs#L20).

RDA archives are organized in blocks [as described here](https://github.com/lysannschlegel/RDAExplorer/wiki/RDA-File-Format). When writing back, the individual files are grouped by file extension, but that was probably different in the original RDA archive.

In your example (data17.rda from Anno 2205): It reads in 9690 files from 93 blocks (you can see that in the status bar at the bottom of the window after opening the archive).
When opening data172.rda it reads 9690 files in 25 blocks instead.
So all files are there, but there are far fewer blocks because there are only 25 different file types in the archive and because in the oroginal archive there are a few empty blocks.

**Comment by lysanntranvouez** [comment]
You can download the latest exe here: https://github.com/lysannschlegel/RDAExplorer/releases
