### ISSUE TITLE
Load failed: Incorrect file format

### ISSUE THREAD

**Issue by Akis26** [lysannschlegel/RDAExplorer#2]
I tried to use anyone of RDAExpoler versions but I have problem (maybe) with compression save game file. My purpose is to disappear the red exclamation mark and the text at the bottom "Unknown Profile" in Anno 1404.
1.  I tried to extract “game2.xml” to desktop from a save game file “namesave.sww”.
2.  Then open “game2.xml” with Notepad++ to change some parameters and save it.
3.  Delete the old “game2.xml” in RDAExpoler and Add the new edit file “game2.xml” from desktop.
4.  Save four files in RDAExpoler with default compression settings.
5.  End, drop the new “namesave.sww” into the folder with other save games directory.
6.  Run Anno 1404.The red exclamation mark and the text at the bottom "Unknown Profile" at edited      “namesave.sww” does not appear.
7.  When choice to Load the edited “namesave.sww” appear a new small window “Load failed: Incorrect file format”.

**Comment by lysanntranvouez** [comment]
I have never tried loading or saving sww files before, but I can indeed reproduce the issue you describe with an old 1404 save game.
Even when I don't change any file inside the sww, when I just load and re-save without compression, an error pops up when trying to load the save game in the game.

I'll look into it now, trying to figure out which file format difference triggers the issue.

**Comment by lysanntranvouez** [comment]
Update about my findings: The issue seems to be a few bytes in the sww file that I'm not entirely sure what they represent.
But it seems as if they might be a checksum to prevent tinkering with the save files. Because if I change only one of these bytes, the "invalid file format" error will pop up.

This version of the RDAExplorer for Anno 1404, 2070 and 2205 is based on one that supported 1404 and 2070 only. So I tried to just re-save a valid sww file with the old one, but I got the same error, even though there are [instructions in the wikia](http://anno1404.wikia.com/wiki/Savegame_editing) on how to edit sww files, referencing the RDAExplorer.
Maybe that was yet another version of the RDAExplorer, that supported this? Unfortunately the link in the wiki page is dead.
Or maybe the game was patched later on, to prevent editing save files, because you could easily unlock all achievements through that?

**Comment by Akis26** [comment]
Thank you very much for your interest!! I tried to follow the instructions but I had no success. Don't matter, i have started to playing the game from beginning.
